apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argo
  template:
    metadata:
      labels:
        app: argo
    spec:
      containers:
      - image: raj786/myrepo:argodemo
        name: argo
        ports:
        - containerPort: 80
